services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    environment:
      #- PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:64
      - NVIDIA_VISIBLE_DEVICES=all
      - gpus=all
      #- OLLAMA_DEBUG=1
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all      
    healthcheck:
      test: ollama list || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - ollama_network

  ollama-models-pull:
    container_name: ollama-models-pull
    image: curlimages/curl:latest
    command: >
      http://ollama:11434/api/pull -d '{"name":"qwen2.5:1.5b"}'
    # command: >
    #   /bin/sh -c "
    #     curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"qwen2.5:1.5b\"}' &&
    #     curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"llama3.2\"}'
    #   "
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - ollama_network

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: appstreamlitchat
    image: streamlitchat
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - STREAMLIT_SERVER_RUN_ON_SAVE=True
    depends_on:
      ollama-models-pull:
        condition: service_completed_successfully
      ollama:
        condition: service_healthy
    networks:
      - ollama_network
    ports:
      - 8002:8002
    volumes:
      - ./app:/usr/app:rw

networks:
  ollama_network:
    driver: bridge
